# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='academco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Academico'),
        ),
    ]
