# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='asignaturas',
            field=models.ManyToManyField(to='common.Asignatura'),
        ),
    ]
